; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.30501.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?value@?$integral_constant@_N$0A@@std@@2_NB	; std::integral_constant<bool,0>::value
PUBLIC	?value@?$integral_constant@_N$00@std@@2_NB	; std::integral_constant<bool,1>::value
;	COMDAT ?value@?$integral_constant@_N$00@std@@2_NB
CONST	SEGMENT
?value@?$integral_constant@_N$00@std@@2_NB DB 01H	; std::integral_constant<bool,1>::value
CONST	ENDS
;	COMDAT ?value@?$integral_constant@_N$0A@@std@@2_NB
CONST	SEGMENT
?value@?$integral_constant@_N$0A@@std@@2_NB DB 00H	; std::integral_constant<bool,0>::value
CONST	ENDS
PUBLIC	?MissingSuiteError@AEGP_SuiteHandler@@AEBAXXZ	; AEGP_SuiteHandler::MissingSuiteError
PUBLIC	_TI1J
PUBLIC	_CTA1J
PUBLIC	??_R0J@8					; long `RTTI Type Descriptor'
PUBLIC	_CT??_R0J@84
EXTRN	_CxxThrowException:PROC
EXTRN	??_7type_info@@6B@:BYTE				; type_info::`vftable'
pdata	SEGMENT
$pdata$?MissingSuiteError@AEGP_SuiteHandler@@AEBAXXZ DD imagerel $LN3
	DD	imagerel $LN3+47
	DD	imagerel $unwind$?MissingSuiteError@AEGP_SuiteHandler@@AEBAXXZ
pdata	ENDS
;	COMDAT _CT??_R0J@84
xdata$x	SEGMENT
_CT??_R0J@84 DD	01H
	DD	imagerel ??_R0J@8
	DD	00H
	DD	0ffffffffH
	ORG $+4
	DD	04H
	DD	00H
xdata$x	ENDS
;	COMDAT ??_R0J@8
data$r	SEGMENT
??_R0J@8 DQ	FLAT:??_7type_info@@6B@			; long `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.J', 00H
data$r	ENDS
;	COMDAT _CTA1J
xdata$x	SEGMENT
_CTA1J	DD	01H
	DD	imagerel _CT??_R0J@84
xdata$x	ENDS
;	COMDAT _TI1J
xdata$x	SEGMENT
_TI1J	DD	00H
	DD	00H
	DD	00H
	DD	imagerel _CTA1J
xdata$x	ENDS
xdata	SEGMENT
$unwind$?MissingSuiteError@AEGP_SuiteHandler@@AEBAXXZ DD 010901H
	DD	06209H
xdata	ENDS
; Function compile flags: /Odtp
; File c:\users\syuilo\documents\visual studio 2013\projects\after_effects_cs5_sdk_win\adobe after effects cs5 win sdk\examples\util\missingsuiteerror.cpp
_TEXT	SEGMENT
poop$ = 32
$T1 = 36
this$ = 64
?MissingSuiteError@AEGP_SuiteHandler@@AEBAXXZ PROC	; AEGP_SuiteHandler::MissingSuiteError

; 25   : {

$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 26   : 	//	Yes, we've read Scott Meyers, and know throwing
; 27   : 	//	a stack-based object can cause problems. Since
; 28   : 	//	the err is just a long, and since we aren't de-
; 29   : 	//	referencing it in any way, risk is mimimal.
; 30   : 
; 31   : 	//	As always, we expect those of you who use
; 32   : 	//	exception-based code to do a little less rudi-
; 33   : 	//	mentary job of it than we are here. 
; 34   : 	
; 35   : 	//	Also, excuse the Madagascar-inspired monkey 
; 36   : 	//	joke; couldn't resist. 
; 37   : 	//								-bbb 10/10/05
; 38   : 	
; 39   : 	PF_Err poop = PF_Err_BAD_CALLBACK_PARAM;

	mov	DWORD PTR poop$[rsp], 516		; 00000204H

; 40   : 
; 41   : 	throw poop;

	mov	eax, DWORD PTR poop$[rsp]
	mov	DWORD PTR $T1[rsp], eax
	lea	rdx, OFFSET FLAT:_TI1J
	lea	rcx, QWORD PTR $T1[rsp]
	call	_CxxThrowException
$LN2@MissingSui:

; 42   : }

	add	rsp, 56					; 00000038H
	ret	0
?MissingSuiteError@AEGP_SuiteHandler@@AEBAXXZ ENDP	; AEGP_SuiteHandler::MissingSuiteError
_TEXT	ENDS
END
