; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.30501.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?value@?$integral_constant@_N$0A@@std@@2_NB	; std::integral_constant<bool,0>::value
PUBLIC	?value@?$integral_constant@_N$00@std@@2_NB	; std::integral_constant<bool,1>::value
;	COMDAT ?value@?$integral_constant@_N$00@std@@2_NB
CONST	SEGMENT
?value@?$integral_constant@_N$00@std@@2_NB DB 01H	; std::integral_constant<bool,1>::value
CONST	ENDS
;	COMDAT ?value@?$integral_constant@_N$0A@@std@@2_NB
CONST	SEGMENT
?value@?$integral_constant@_N$0A@@std@@2_NB DB 00H	; std::integral_constant<bool,0>::value
CONST	ENDS
CONST	SEGMENT
$SG117805 DB	'%s v%d.%d', 0dH, '%s', 00H
	ORG $+3
$SG117840 DB	'Block size', 00H
	ORG $+5
$SG117855 DB	'Vibration', 00H
	ORG $+6
$SG117870 DB	'Random seed', 00H
$SG117885 DB	'Merge', 00H
	ORG $+6
$SG117886 DB	094H, 'w', 08cH, 'i', 082H, 0c6H, 08dH, 087H, 090H, 0acH, 082H
	DB	0b5H, 082H, 0dcH, 082H, 0b7H, 081H, 'B', 00H
CONST	ENDS
PUBLIC	?LoadSuite@AEGP_SuiteHandler@@AEBAPEAXPEADJ@Z	; AEGP_SuiteHandler::LoadSuite
PUBLIC	?ANSICallbacksSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_ANSICallbacksSuite1@@XZ ; AEGP_SuiteHandler::ANSICallbacksSuite1
PUBLIC	?HandleSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_HandleSuite1@@XZ ; AEGP_SuiteHandler::HandleSuite1
PUBLIC	EntryPointFunc
PUBLIC	??_C@_0O@JPGHEGPP@PF?5ANSI?5Suite?$AA@		; `string'
PUBLIC	??_C@_0BA@CLDKMHPO@PF?5Handle?5Suite?$AA@	; `string'
PUBLIC	??_R0J@8					; long `RTTI Type Descriptor'
EXTRN	strlen:PROC
EXTRN	__imp_rand:PROC
EXTRN	__imp_srand:PROC
EXTRN	GetStringPtr:PROC
EXTRN	?MissingSuiteError@AEGP_SuiteHandler@@AEBAXXZ:PROC ; AEGP_SuiteHandler::MissingSuiteError
EXTRN	??0AEGP_SuiteHandler@@QEAA@PEBUSPBasicSuite@@@Z:PROC ; AEGP_SuiteHandler::AEGP_SuiteHandler
EXTRN	??1AEGP_SuiteHandler@@QEAA@XZ:PROC		; AEGP_SuiteHandler::~AEGP_SuiteHandler
EXTRN	__CxxFrameHandler3:PROC
EXTRN	__GSHandlerCheck:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	??_7type_info@@6B@:BYTE				; type_info::`vftable'
EXTRN	__ImageBase:BYTE
EXTRN	__security_cookie:QWORD
EXTRN	_fltused:DWORD
;	COMDAT pdata
pdata	SEGMENT
$pdata$?LoadSuite@AEGP_SuiteHandler@@AEBAPEAXPEADJ@Z DD imagerel $LN5
	DD	imagerel $LN5+82
	DD	imagerel $unwind$?LoadSuite@AEGP_SuiteHandler@@AEBAPEAXPEADJ@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?ANSICallbacksSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_ANSICallbacksSuite1@@XZ DD imagerel $LN4
	DD	imagerel $LN4+76
	DD	imagerel $unwind$?ANSICallbacksSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_ANSICallbacksSuite1@@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?HandleSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_HandleSuite1@@XZ DD imagerel $LN4
	DD	imagerel $LN4+76
	DD	imagerel $unwind$?HandleSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_HandleSuite1@@XZ
pdata	ENDS
pdata	SEGMENT
$pdata$EntryPointFunc DD imagerel $LN19
	DD	imagerel $LN19+516
	DD	imagerel $unwind$EntryPointFunc
pdata	ENDS
pdata	SEGMENT
$pdata$EntryPointFunc$catch$0 DD imagerel EntryPointFunc$catch$0
	DD	imagerel EntryPointFunc$catch$0+36
	DD	imagerel $unwind$EntryPointFunc$catch$0
pdata	ENDS
pdata	SEGMENT
$pdata$?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z DD imagerel ?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
	DD	imagerel ?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z+197
	DD	imagerel $unwind$?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
pdata	ENDS
pdata	SEGMENT
$pdata$?dtor$0@?0??About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA DD imagerel ?dtor$0@?0??About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA
	DD	imagerel ?dtor$0@?0??About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA+24
	DD	imagerel $unwind$?dtor$0@?0??About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA
pdata	ENDS
pdata	SEGMENT
$pdata$?ParamsSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z DD imagerel ?ParamsSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
	DD	imagerel ?ParamsSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z+1296
	DD	imagerel $unwind$?ParamsSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
$pdata$?FrameSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z DD imagerel ?FrameSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
	DD	imagerel ?FrameSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z+183
	DD	imagerel $unwind$?FrameSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
$pdata$?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z DD imagerel ?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
	DD	imagerel ?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z+891
	DD	imagerel $unwind$?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
pdata	ENDS
pdata	SEGMENT
$pdata$?dtor$0@?0??Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA DD imagerel ?dtor$0@?0??Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA
	DD	imagerel ?dtor$0@?0??Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA+27
	DD	imagerel $unwind$?dtor$0@?0??Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA
pdata	ENDS
pdata	SEGMENT
$pdata$?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z DD imagerel ?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z
	DD	imagerel ?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z+507
	DD	imagerel $unwind$?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z
pdata	ENDS
pdata	SEGMENT
$pdata$?dtor$0@?0??DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z@4HA DD imagerel ?dtor$0@?0??DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z@4HA
	DD	imagerel ?dtor$0@?0??DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z@4HA+27
	DD	imagerel $unwind$?dtor$0@?0??DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z@4HA
pdata	ENDS
pdata	SEGMENT
$pdata$?QueryDynamicFlags@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z DD imagerel ?QueryDynamicFlags@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z
	DD	imagerel ?QueryDynamicFlags@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z+368
	DD	imagerel $unwind$?QueryDynamicFlags@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z
pdata	ENDS
;	COMDAT ??_R0J@8
data$r	SEGMENT
??_R0J@8 DQ	FLAT:??_7type_info@@6B@			; long `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.J', 00H
data$r	ENDS
;	COMDAT ??_C@_0BA@CLDKMHPO@PF?5Handle?5Suite?$AA@
CONST	SEGMENT
??_C@_0BA@CLDKMHPO@PF?5Handle?5Suite?$AA@ DB 'PF Handle Suite', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0O@JPGHEGPP@PF?5ANSI?5Suite?$AA@
CONST	SEGMENT
??_C@_0O@JPGHEGPP@PF?5ANSI?5Suite?$AA@ DB 'PF ANSI Suite', 00H ; `string'
CONST	ENDS
CONST	SEGMENT
	ORG $+5
$cppxdata$EntryPointFunc DD 019930522H
	DD	02H
	DD	imagerel $stateUnwindMap$EntryPointFunc
	DD	01H
	DD	imagerel $tryMap$EntryPointFunc
	DD	06H
	DD	imagerel $ip2state$EntryPointFunc
	DD	048H
	DD	00H
	DD	01H
$cppxdata$?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z DD 019930522H
	DD	01H
	DD	imagerel $stateUnwindMap$?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
	DD	00H
	DD	00H
	DD	03H
	DD	imagerel $ip2state$?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
	DD	050H
	DD	00H
	DD	01H
$cppxdata$?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z DD 019930522H
	DD	01H
	DD	imagerel $stateUnwindMap$?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
	DD	00H
	DD	00H
	DD	03H
	DD	imagerel $ip2state$?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
	DD	0a8H
	DD	00H
	DD	01H
$cppxdata$?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z DD 019930522H
	DD	01H
	DD	imagerel $stateUnwindMap$?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z
	DD	00H
	DD	00H
	DD	03H
	DD	imagerel $ip2state$?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z
	DD	070H
	DD	00H
	DD	01H
CONST	ENDS
xdata	SEGMENT
$unwind$EntryPointFunc DD 012019H
	DD	0c217H
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$EntryPointFunc
$stateUnwindMap$EntryPointFunc DD 0ffffffffH
	DD	00H
	DD	0ffffffffH
	DD	00H
$tryMap$EntryPointFunc DD 00H
	DD	00H
	DD	01H
	DD	01H
	DD	imagerel $handlerMap$0$EntryPointFunc
$handlerMap$0$EntryPointFunc DD 08H
	DD	FLAT:??_R0J@8
	DD	050H
	DD	imagerel EntryPointFunc$catch$0
	DD	038H
$ip2state$EntryPointFunc DD imagerel EntryPointFunc
	DD	0ffffffffH
	DD	imagerel EntryPointFunc+40
	DD	00H
	DD	imagerel EntryPointFunc+429
	DD	0ffffffffH
	DD	imagerel EntryPointFunc+440
	DD	00H
	DD	imagerel EntryPointFunc$catch$0+13
	DD	01H
	DD	imagerel EntryPointFunc$catch$0+22
	DD	00H
$unwind$EntryPointFunc$catch$0 DD 020a19H
	DD	05006320aH
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$EntryPointFunc
$unwind$?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z DD 022411H
	DD	079011bH
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
$stateUnwindMap$?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z DD 0ffffffffH
	DD	imagerel ?dtor$0@?0??About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA
$ip2state$?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z DD imagerel ?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
	DD	0ffffffffH
	DD	imagerel ?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z+62
	DD	00H
	DD	imagerel ?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z+175
	DD	0ffffffffH
$unwind$?dtor$0@?0??About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA DD 020601H
	DD	050023206H
$unwind$?ParamsSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z DD 022d19H
	DD	02b011bH
	DD	imagerel __GSHandlerCheck
	DD	0140H
$unwind$?FrameSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z DD 011801H
	DD	04218H
$unwind$?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z DD 022711H
	DD	083011bH
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
$stateUnwindMap$?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z DD 0ffffffffH
	DD	imagerel ?dtor$0@?0??Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA
$ip2state$?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z DD imagerel ?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z
	DD	0ffffffffH
	DD	imagerel ?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z+79
	DD	00H
	DD	imagerel ?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z+866
	DD	0ffffffffH
$unwind$?dtor$0@?0??Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA DD 020601H
	DD	050023206H
$unwind$?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z DD 022411H
	DD	07d011bH
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z
$stateUnwindMap$?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z DD 0ffffffffH
	DD	imagerel ?dtor$0@?0??DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z@4HA
$ip2state$?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z DD imagerel ?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z
	DD	0ffffffffH
	DD	imagerel ?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z+95
	DD	00H
	DD	imagerel ?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z+482
	DD	0ffffffffH
$unwind$?dtor$0@?0??DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z@4HA DD 020601H
	DD	050023206H
$unwind$?QueryDynamicFlags@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z DD 022d19H
	DD	021011bH
	DD	imagerel __GSHandlerCheck
	DD	0f0H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?HandleSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_HandleSuite1@@XZ DD 010901H
	DD	04209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?ANSICallbacksSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_ANSICallbacksSuite1@@XZ DD 010901H
	DD	04209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?LoadSuite@AEGP_SuiteHandler@@AEBAPEAXPEADJ@Z DD 011301H
	DD	06213H
xdata	ENDS
; Function compile flags: /Odtp
; File c:\users\syuilo\documents\visual studio 2013\projects\after_effects_cs5_sdk_win\adobe after effects cs5 win sdk\examples\template\moonface\skeleton.cpp
_TEXT	SEGMENT
err$ = 32
err2$ = 36
_t$1 = 40
tv66 = 44
_p$2 = 48
def$ = 64
__$ArrayPad$ = 240
in_data$ = 272
out_data$ = 280
params$ = 288
extra$ = 296
?QueryDynamicFlags@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z PROC ; QueryDynamicFlags

; 313  : {

	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 264				; 00000108H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax

; 314  :     PF_Err 		err = PF_Err_NONE,

	mov	DWORD PTR err$[rsp], 0

; 315  :         err2 = PF_Err_NONE;

	mov	DWORD PTR err2$[rsp], 0
$LN12@QueryDynam:

; 316  :     PF_ParamDef def;
; 317  : 
; 318  :     AEFX_CLR_STRUCT(def);

	mov	DWORD PTR _t$1[rsp], 176		; 000000b0H
	lea	rax, QWORD PTR def$[rsp]
	mov	QWORD PTR _p$2[rsp], rax
$LN9@QueryDynam:
	mov	eax, DWORD PTR _t$1[rsp]
	mov	DWORD PTR tv66[rsp], eax
	mov	eax, DWORD PTR _t$1[rsp]
	dec	eax
	mov	DWORD PTR _t$1[rsp], eax
	cmp	DWORD PTR tv66[rsp], 0
	je	SHORT $LN8@QueryDynam
	mov	rax, QWORD PTR _p$2[rsp]
	mov	BYTE PTR [rax], 0
	mov	rax, QWORD PTR _p$2[rsp]
	inc	rax
	mov	QWORD PTR _p$2[rsp], rax
	jmp	SHORT $LN9@QueryDynam
$LN8@QueryDynam:
	xor	eax, eax
	test	eax, eax
	jne	SHORT $LN12@QueryDynam

; 319  : 
; 320  :     /*	The parameter array passed with PF_Cmd_QUERY_DYNAMIC_FLAGS
; 321  :         contains invalid values; use PF_CHECKOUT_PARAM() to obtain
; 322  :         real values.
; 323  :         */
; 324  : 
; 325  :     if (!err){

	cmp	DWORD PTR err$[rsp], 0
	jne	$LN7@QueryDynam

; 326  :         // if it's checked
; 327  :         if (def.u.bd.value)	{

	cmp	DWORD PTR def$[rsp+56], 0
	je	SHORT $LN6@QueryDynam

; 328  :             out_data->out_flags2 |= PF_OutFlag2_I_USE_3D_LIGHTS;

	mov	rax, QWORD PTR out_data$[rsp]
	mov	eax, DWORD PTR [rax+400]
	or	eax, 4
	mov	rcx, QWORD PTR out_data$[rsp]
	mov	DWORD PTR [rcx+400], eax

; 329  :             out_data->out_flags2 |= PF_OutFlag2_I_USE_3D_CAMERA;

	mov	rax, QWORD PTR out_data$[rsp]
	mov	eax, DWORD PTR [rax+400]
	or	eax, 2
	mov	rcx, QWORD PTR out_data$[rsp]
	mov	DWORD PTR [rcx+400], eax

; 330  :         }
; 331  :         else {

	jmp	SHORT $LN5@QueryDynam
$LN6@QueryDynam:

; 332  :             out_data->out_flags2 &= ~PF_OutFlag2_I_USE_3D_LIGHTS;

	mov	rax, QWORD PTR out_data$[rsp]
	mov	eax, DWORD PTR [rax+400]
	and	eax, -5
	mov	rcx, QWORD PTR out_data$[rsp]
	mov	DWORD PTR [rcx+400], eax

; 333  :             out_data->out_flags2 &= ~PF_OutFlag2_I_USE_3D_CAMERA;

	mov	rax, QWORD PTR out_data$[rsp]
	mov	eax, DWORD PTR [rax+400]
	and	eax, -3
	mov	rcx, QWORD PTR out_data$[rsp]
	mov	DWORD PTR [rcx+400], eax
$LN5@QueryDynam:
$LN7@QueryDynam:
$LN4@QueryDynam:

; 334  :         }
; 335  :     }
; 336  :     ERR2(PF_CHECKIN_PARAM(in_data, &def));

	lea	rdx, QWORD PTR def$[rsp]
	mov	rax, QWORD PTR in_data$[rsp]
	mov	rcx, QWORD PTR [rax+184]
	mov	rax, QWORD PTR in_data$[rsp]
	call	QWORD PTR [rax+8]
	mov	DWORD PTR err2$[rsp], eax
	cmp	DWORD PTR err2$[rsp], 0
	je	SHORT $LN1@QueryDynam
	cmp	DWORD PTR err$[rsp], 0
	jne	SHORT $LN1@QueryDynam
	mov	eax, DWORD PTR err2$[rsp]
	mov	DWORD PTR err$[rsp], eax
$LN1@QueryDynam:
	xor	eax, eax
	test	eax, eax
	jne	SHORT $LN4@QueryDynam

; 337  :     return err;

	mov	eax, DWORD PTR err$[rsp]

; 338  : }

	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 264				; 00000108H
	ret	0
?QueryDynamicFlags@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z ENDP ; QueryDynamicFlags
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\syuilo\documents\visual studio 2013\projects\after_effects_cs5_sdk_win\adobe after effects cs5 win sdk\examples\template\moonface\skeleton.cpp
_TEXT	SEGMENT
msgH$ = 32
tv70 = 40
$T1 = 44
err$ = 48
extraP$ = 56
tv87 = 64
tv154 = 72
tv81 = 80
tv161 = 88
tv141 = 96
tv135 = 104
$T2 = 112
suites$ = 128
in_data$ = 1008
out_data$ = 1016
params$ = 1024
extra$ = 1032
?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z PROC ; DescribeDependencies

; 267  : {

	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 1000				; 000003e8H
	mov	QWORD PTR $T2[rsp], -2

; 268  :     PF_Err						err = PF_Err_NONE;

	mov	DWORD PTR err$[rsp], 0

; 269  :     PF_ExtDependenciesExtra		*extraP = (PF_ExtDependenciesExtra*)extra;

	mov	rax, QWORD PTR extra$[rsp]
	mov	QWORD PTR extraP$[rsp], rax

; 270  :     PF_Handle					msgH = NULL;

	mov	QWORD PTR msgH$[rsp], 0

; 271  : 
; 272  :     AEGP_SuiteHandler suites(in_data->pica_basicP);

	mov	rax, QWORD PTR in_data$[rsp]
	mov	rdx, QWORD PTR [rax+384]
	lea	rcx, QWORD PTR suites$[rsp]
	call	??0AEGP_SuiteHandler@@QEAA@PEBUSPBasicSuite@@@Z ; AEGP_SuiteHandler::AEGP_SuiteHandler
	npad	1

; 273  : 
; 274  :     switch (extraP->check_type)

	mov	rax, QWORD PTR extraP$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	DWORD PTR tv70[rsp], eax
	cmp	DWORD PTR tv70[rsp], 1
	je	SHORT $LN5@DescribeDe
	cmp	DWORD PTR tv70[rsp], 2
	je	SHORT $LN4@DescribeDe
	jmp	$LN2@DescribeDe
$LN5@DescribeDe:

; 275  :     {
; 276  : 
; 277  :     case PF_DepCheckType_ALL_DEPENDENCIES:
; 278  : 
; 279  :         msgH = suites.HandleSuite1()->host_new_handle((A_long)strlen(STR(StrID_DependString1)) + 1);

	mov	ecx, 6
	call	GetStringPtr
	mov	rcx, rax
	call	strlen
	inc	eax
	cdqe
	mov	QWORD PTR tv81[rsp], rax
	lea	rcx, QWORD PTR suites$[rsp]
	call	?HandleSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_HandleSuite1@@XZ ; AEGP_SuiteHandler::HandleSuite1
	mov	rcx, QWORD PTR tv81[rsp]
	call	QWORD PTR [rax]
	mov	QWORD PTR msgH$[rsp], rax

; 280  :         suites.ANSICallbacksSuite1()->strcpy(reinterpret_cast<char*>(DH(msgH)), STR(StrID_DependString1));

	mov	ecx, 6
	call	GetStringPtr
	mov	QWORD PTR tv87[rsp], rax
	lea	rcx, QWORD PTR suites$[rsp]
	call	?ANSICallbacksSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_ANSICallbacksSuite1@@XZ ; AEGP_SuiteHandler::ANSICallbacksSuite1
	mov	rcx, QWORD PTR tv87[rsp]
	mov	rdx, rcx
	mov	rcx, QWORD PTR msgH$[rsp]
	mov	rcx, QWORD PTR [rcx]
	call	QWORD PTR [rax+128]

; 281  :         break;

	jmp	$LN6@DescribeDe
$LN4@DescribeDe:

; 282  : 
; 283  :     case PF_DepCheckType_MISSING_DEPENDENCIES:
; 284  : 
; 285  :         // about one ninth of the time, something's missing 
; 286  : 
; 287  :         if (rand() % 9)	{

	call	QWORD PTR __imp_rand
	cdq
	mov	ecx, 9
	idiv	ecx
	mov	eax, edx
	test	eax, eax
	je	SHORT $LN3@DescribeDe

; 288  :             msgH = suites.HandleSuite1()->host_new_handle((A_long)strlen(STR(StrID_DependString2)) + 1);

	mov	ecx, 7
	call	GetStringPtr
	mov	rcx, rax
	call	strlen
	inc	eax
	cdqe
	mov	QWORD PTR tv135[rsp], rax
	lea	rcx, QWORD PTR suites$[rsp]
	call	?HandleSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_HandleSuite1@@XZ ; AEGP_SuiteHandler::HandleSuite1
	mov	rcx, QWORD PTR tv135[rsp]
	call	QWORD PTR [rax]
	mov	QWORD PTR msgH$[rsp], rax

; 289  :             suites.ANSICallbacksSuite1()->strcpy(reinterpret_cast<char*>(DH(msgH)), STR(StrID_DependString2));

	mov	ecx, 7
	call	GetStringPtr
	mov	QWORD PTR tv141[rsp], rax
	lea	rcx, QWORD PTR suites$[rsp]
	call	?ANSICallbacksSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_ANSICallbacksSuite1@@XZ ; AEGP_SuiteHandler::ANSICallbacksSuite1
	mov	rcx, QWORD PTR tv141[rsp]
	mov	rdx, rcx
	mov	rcx, QWORD PTR msgH$[rsp]
	mov	rcx, QWORD PTR [rcx]
	call	QWORD PTR [rax+128]
$LN3@DescribeDe:

; 290  :         }
; 291  :         break;

	jmp	SHORT $LN6@DescribeDe
$LN2@DescribeDe:

; 292  : 
; 293  :     default:
; 294  :         msgH = suites.HandleSuite1()->host_new_handle((A_long)strlen(STR(StrID_NONE)) + 1);

	xor	ecx, ecx
	call	GetStringPtr
	mov	rcx, rax
	call	strlen
	inc	eax
	cdqe
	mov	QWORD PTR tv154[rsp], rax
	lea	rcx, QWORD PTR suites$[rsp]
	call	?HandleSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_HandleSuite1@@XZ ; AEGP_SuiteHandler::HandleSuite1
	mov	rcx, QWORD PTR tv154[rsp]
	call	QWORD PTR [rax]
	mov	QWORD PTR msgH$[rsp], rax

; 295  :         if (msgH){

	cmp	QWORD PTR msgH$[rsp], 0
	je	SHORT $LN6@DescribeDe

; 296  :             suites.ANSICallbacksSuite1()->strcpy(reinterpret_cast<char*>(DH(msgH)), STR(StrID_NONE));

	xor	ecx, ecx
	call	GetStringPtr
	mov	QWORD PTR tv161[rsp], rax
	lea	rcx, QWORD PTR suites$[rsp]
	call	?ANSICallbacksSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_ANSICallbacksSuite1@@XZ ; AEGP_SuiteHandler::ANSICallbacksSuite1
	mov	rcx, QWORD PTR tv161[rsp]
	mov	rdx, rcx
	mov	rcx, QWORD PTR msgH$[rsp]
	mov	rcx, QWORD PTR [rcx]
	call	QWORD PTR [rax+128]
$LN6@DescribeDe:

; 297  :         }
; 298  :         break;
; 299  : 
; 300  :     }
; 301  : 
; 302  :     extraP->dependencies_strH = msgH;

	mov	rax, QWORD PTR extraP$[rsp]
	mov	rcx, QWORD PTR msgH$[rsp]
	mov	QWORD PTR [rax+8], rcx

; 303  : 
; 304  :     return err;

	mov	eax, DWORD PTR err$[rsp]
	mov	DWORD PTR $T1[rsp], eax
	lea	rcx, QWORD PTR suites$[rsp]
	call	??1AEGP_SuiteHandler@@QEAA@XZ		; AEGP_SuiteHandler::~AEGP_SuiteHandler
	mov	eax, DWORD PTR $T1[rsp]

; 305  : }

	add	rsp, 1000				; 000003e8H
	ret	0
?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z ENDP ; DescribeDependencies
_TEXT	ENDS
; Function compile flags: /Odtp
text$x	SEGMENT
msgH$ = 32
tv70 = 40
$T1 = 44
err$ = 48
extraP$ = 56
tv87 = 64
tv154 = 72
tv81 = 80
tv161 = 88
tv141 = 96
tv135 = 104
$T2 = 112
suites$ = 128
in_data$ = 1008
out_data$ = 1016
params$ = 1024
extra$ = 1032
?dtor$0@?0??DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z@4HA PROC ; `DescribeDependencies'::`1'::dtor$0
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
	lea	rcx, QWORD PTR suites$[rbp]
	call	??1AEGP_SuiteHandler@@QEAA@XZ		; AEGP_SuiteHandler::~AEGP_SuiteHandler
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
?dtor$0@?0??DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z@4HA ENDP ; `DescribeDependencies'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Odtp
; File c:\users\syuilo\documents\visual studio 2013\projects\after_effects_cs5_sdk_win\adobe after effects cs5 win sdk\examples\template\moonface\skeleton.cpp
_TEXT	SEGMENT
tv138 = 48
merge$ = 49
size$ = 52
x$1 = 56
y$2 = 60
iy$3 = 64
ix$4 = 68
xtile$ = 72
sety$5 = 76
setx$6 = 80
py$7 = 84
vibration$ = 88
input$ = 96
px$8 = 104
height$ = 108
width$ = 112
inWidth$ = 116
$T9 = 120
xr$10 = 124
ytile$ = 128
seed$ = 132
yr$11 = 136
err$ = 140
outWidth$ = 144
inData$ = 152
outData$ = 160
$T12 = 168
suites$ = 176
in_data$ = 1056
out_data$ = 1064
params$ = 1072
output$ = 1080
?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z PROC ; Render

; 175  : {

	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 1048				; 00000418H
	mov	QWORD PTR $T12[rsp], -2

; 176  :     PF_Err				err = PF_Err_NONE;

	mov	DWORD PTR err$[rsp], 0

; 177  :     AEGP_SuiteHandler	suites(in_data->pica_basicP);

	mov	rax, QWORD PTR in_data$[rsp]
	mov	rdx, QWORD PTR [rax+384]
	lea	rcx, QWORD PTR suites$[rsp]
	call	??0AEGP_SuiteHandler@@QEAA@PEBUSPBasicSuite@@@Z ; AEGP_SuiteHandler::AEGP_SuiteHandler
	npad	1

; 178  : 
; 179  :     PF_EffectWorld *input = &params[MOONFACE_INPUT]->u.ld;

	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR params$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	add	rax, 56					; 00000038H
	mov	QWORD PTR input$[rsp], rax

; 180  : 
; 181  : 
; 182  :     PF_Pixel *outData = (PF_Pixel *)output->data;

	mov	rax, QWORD PTR output$[rsp]
	mov	rax, QWORD PTR [rax+24]
	mov	QWORD PTR outData$[rsp], rax

; 183  :     PF_Pixel *inData = (PF_Pixel *)input->data;

	mov	rax, QWORD PTR input$[rsp]
	mov	rax, QWORD PTR [rax+24]
	mov	QWORD PTR inData$[rsp], rax

; 184  : 
; 185  :     A_long width = input->width;

	mov	rax, QWORD PTR input$[rsp]
	mov	eax, DWORD PTR [rax+36]
	mov	DWORD PTR width$[rsp], eax

; 186  :     A_long height = input->height;

	mov	rax, QWORD PTR input$[rsp]
	mov	eax, DWORD PTR [rax+40]
	mov	DWORD PTR height$[rsp], eax

; 187  :     A_long outWidth = output->rowbytes / sizeof(PF_Pixel);

	mov	rax, QWORD PTR output$[rsp]
	movsxd	rax, DWORD PTR [rax+32]
	xor	edx, edx
	mov	ecx, 4
	div	rcx
	mov	DWORD PTR outWidth$[rsp], eax

; 188  :     A_long inWidth = input->rowbytes / sizeof(PF_Pixel);

	mov	rax, QWORD PTR input$[rsp]
	movsxd	rax, DWORD PTR [rax+32]
	xor	edx, edx
	mov	ecx, 4
	div	rcx
	mov	DWORD PTR inWidth$[rsp], eax

; 189  : 
; 190  : 
; 191  : 
; 192  :     int size = params[MOONFACE_SIZE]->u.sd.value;

	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR params$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	eax, DWORD PTR [rax+56]
	mov	DWORD PTR size$[rsp], eax

; 193  :     int vibration = params[MOONFACE_VIBRATION]->u.sd.value;

	mov	eax, 8
	imul	rax, rax, 2
	mov	rcx, QWORD PTR params$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	eax, DWORD PTR [rax+56]
	mov	DWORD PTR vibration$[rsp], eax

; 194  :     int seed = params[MOONFACE_SEED]->u.sd.value;

	mov	eax, 8
	imul	rax, rax, 3
	mov	rcx, QWORD PTR params$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	eax, DWORD PTR [rax+56]
	mov	DWORD PTR seed$[rsp], eax

; 195  :     bool merge = params[MOONFACE_MERGE]->u.bd.value;

	mov	eax, 8
	imul	rax, rax, 4
	mov	rcx, QWORD PTR params$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	cmp	DWORD PTR [rax+56], 0
	je	SHORT $LN17@Render
	mov	BYTE PTR tv138[rsp], 1
	jmp	SHORT $LN18@Render
$LN17@Render:
	mov	BYTE PTR tv138[rsp], 0
$LN18@Render:
	movzx	eax, BYTE PTR tv138[rsp]
	mov	BYTE PTR merge$[rsp], al

; 196  : 
; 197  :     if (merge)

	movzx	eax, BYTE PTR merge$[rsp]
	test	eax, eax
	je	SHORT $LN14@Render

; 198  :         PF_COPY(input, output, NULL, NULL);

	mov	rax, QWORD PTR in_data$[rsp]
	mov	rax, QWORD PTR [rax+176]
	mov	QWORD PTR [rsp+32], 0
	xor	r9d, r9d
	mov	r8, QWORD PTR output$[rsp]
	mov	rdx, QWORD PTR input$[rsp]
	mov	rcx, QWORD PTR in_data$[rsp]
	mov	rcx, QWORD PTR [rcx+184]
	call	QWORD PTR [rax+64]
$LN14@Render:

; 199  : 
; 200  :     int xtile;
; 201  :     int ytile;
; 202  :     xtile = ((int)width / size);

	mov	eax, DWORD PTR width$[rsp]
	cdq
	idiv	DWORD PTR size$[rsp]
	mov	DWORD PTR xtile$[rsp], eax

; 203  :     xtile = ((int)height / size);

	mov	eax, DWORD PTR height$[rsp]
	cdq
	idiv	DWORD PTR size$[rsp]
	mov	DWORD PTR xtile$[rsp], eax

; 204  :     xtile = 60;

	mov	DWORD PTR xtile$[rsp], 60		; 0000003cH

; 205  :     ytile = 33;

	mov	DWORD PTR ytile$[rsp], 33		; 00000021H

; 206  : 
; 207  :     srand(seed);

	mov	ecx, DWORD PTR seed$[rsp]
	call	QWORD PTR __imp_srand

; 208  : 
; 209  :     for (int ix = 0; ix < xtile; ix++)

	mov	DWORD PTR ix$4[rsp], 0
	jmp	SHORT $LN13@Render
$LN12@Render:
	mov	eax, DWORD PTR ix$4[rsp]
	inc	eax
	mov	DWORD PTR ix$4[rsp], eax
$LN13@Render:
	mov	eax, DWORD PTR xtile$[rsp]
	cmp	DWORD PTR ix$4[rsp], eax
	jge	$LN11@Render

; 210  :     {
; 211  :         for (int iy = 0; iy < ytile; iy++)

	mov	DWORD PTR iy$3[rsp], 0
	jmp	SHORT $LN10@Render
$LN9@Render:
	mov	eax, DWORD PTR iy$3[rsp]
	inc	eax
	mov	DWORD PTR iy$3[rsp], eax
$LN10@Render:
	mov	eax, DWORD PTR ytile$[rsp]
	cmp	DWORD PTR iy$3[rsp], eax
	jge	$LN8@Render

; 212  :         {
; 213  :             // —h‚ê‚ðŽZo
; 214  :             //int xr = (rand() % vibration) - (vibration / 2);
; 215  :             //int yr = (rand() % vibration) - (vibration / 2);
; 216  :             int xr = (rand() % vibration) / 2;

	call	QWORD PTR __imp_rand
	cdq
	idiv	DWORD PTR vibration$[rsp]
	mov	eax, edx
	cdq
	sub	eax, edx
	sar	eax, 1
	mov	DWORD PTR xr$10[rsp], eax

; 217  :             int yr = (rand() % vibration) / 2;

	call	QWORD PTR __imp_rand
	cdq
	idiv	DWORD PTR vibration$[rsp]
	mov	eax, edx
	cdq
	sub	eax, edx
	sar	eax, 1
	mov	DWORD PTR yr$11[rsp], eax

; 218  : 
; 219  :             for (int x = 0; x < size; x++)

	mov	DWORD PTR x$1[rsp], 0
	jmp	SHORT $LN7@Render
$LN6@Render:
	mov	eax, DWORD PTR x$1[rsp]
	inc	eax
	mov	DWORD PTR x$1[rsp], eax
$LN7@Render:
	mov	eax, DWORD PTR size$[rsp]
	cmp	DWORD PTR x$1[rsp], eax
	jge	$LN5@Render

; 220  :             {
; 221  :                 for (int y = 0; y < size; y++)

	mov	DWORD PTR y$2[rsp], 0
	jmp	SHORT $LN4@Render
$LN3@Render:
	mov	eax, DWORD PTR y$2[rsp]
	inc	eax
	mov	DWORD PTR y$2[rsp], eax
$LN4@Render:
	mov	eax, DWORD PTR size$[rsp]
	cmp	DWORD PTR y$2[rsp], eax
	jge	$LN2@Render

; 222  :                 {
; 223  :                     int px = (ix * size) + x;

	mov	eax, DWORD PTR ix$4[rsp]
	imul	eax, DWORD PTR size$[rsp]
	add	eax, DWORD PTR x$1[rsp]
	mov	DWORD PTR px$8[rsp], eax

; 224  :                     int py = (iy * size) + y;

	mov	eax, DWORD PTR iy$3[rsp]
	imul	eax, DWORD PTR size$[rsp]
	add	eax, DWORD PTR y$2[rsp]
	mov	DWORD PTR py$7[rsp], eax

; 225  : 
; 226  :                     int setx = (px + xr);

	mov	eax, DWORD PTR xr$10[rsp]
	mov	ecx, DWORD PTR px$8[rsp]
	add	ecx, eax
	mov	eax, ecx
	mov	DWORD PTR setx$6[rsp], eax

; 227  :                     int sety = (py + yr);

	mov	eax, DWORD PTR yr$11[rsp]
	mov	ecx, DWORD PTR py$7[rsp]
	add	ecx, eax
	mov	eax, ecx
	mov	DWORD PTR sety$5[rsp], eax

; 228  : 
; 229  :                     // •`‰æ
; 230  :                     if ((setx >= 0) && (setx < width) && (sety >= 0) && (sety < height))

	cmp	DWORD PTR setx$6[rsp], 0
	jl	SHORT $LN1@Render
	mov	eax, DWORD PTR width$[rsp]
	cmp	DWORD PTR setx$6[rsp], eax
	jge	SHORT $LN1@Render
	cmp	DWORD PTR sety$5[rsp], 0
	jl	SHORT $LN1@Render
	mov	eax, DWORD PTR height$[rsp]
	cmp	DWORD PTR sety$5[rsp], eax
	jge	SHORT $LN1@Render

; 231  :                         outData[setx + sety * outWidth] =
; 232  :                         inData[px + py * inWidth];

	mov	eax, DWORD PTR py$7[rsp]
	imul	eax, DWORD PTR inWidth$[rsp]
	mov	ecx, DWORD PTR px$8[rsp]
	add	ecx, eax
	mov	eax, ecx
	cdqe
	mov	rcx, QWORD PTR inData$[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	ecx, DWORD PTR sety$5[rsp]
	imul	ecx, DWORD PTR outWidth$[rsp]
	mov	edx, DWORD PTR setx$6[rsp]
	add	edx, ecx
	mov	ecx, edx
	movsxd	rcx, ecx
	mov	rdx, QWORD PTR outData$[rsp]
	mov	DWORD PTR [rdx+rcx*4], eax
$LN1@Render:

; 233  :                 }

	jmp	$LN3@Render
$LN2@Render:

; 234  :             }

	jmp	$LN6@Render
$LN5@Render:

; 235  :         }

	jmp	$LN9@Render
$LN8@Render:

; 236  :     }

	jmp	$LN12@Render
$LN11@Render:

; 237  : 
; 238  : 
; 239  :     //output->data = (PF_PixelPtr)outData;
; 240  : 
; 241  :     ///*	Put interesting code here. */
; 242  :     //
; 243  :     //// Premiere Pro/Elements doesn't support the PF World Transform Suite,
; 244  :     //// but it does support many of the callbacks in utils
; 245  :     //if (in_data->appl_id != 'PrMr') {
; 246  :     //	ERR(suites.WorldTransformSuite1()->copy(in_data->effect_ref,
; 247  :     //											&params[MOONFACE_INPUT]->u.ld,
; 248  :     //											output,
; 249  :     //											NULL,
; 250  :     //											NULL));
; 251  :     //} else {
; 252  :     //	ERR(PF_COPY(&params[MOONFACE_INPUT]->u.ld,
; 253  :     //				output,
; 254  :     //				NULL,
; 255  :     //				NULL));
; 256  :     //}
; 257  : 
; 258  :     return err;

	mov	eax, DWORD PTR err$[rsp]
	mov	DWORD PTR $T9[rsp], eax
	lea	rcx, QWORD PTR suites$[rsp]
	call	??1AEGP_SuiteHandler@@QEAA@XZ		; AEGP_SuiteHandler::~AEGP_SuiteHandler
	mov	eax, DWORD PTR $T9[rsp]

; 259  : }

	add	rsp, 1048				; 00000418H
	ret	0
?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z ENDP ; Render
_TEXT	ENDS
; Function compile flags: /Odtp
text$x	SEGMENT
tv138 = 48
merge$ = 49
size$ = 52
x$1 = 56
y$2 = 60
iy$3 = 64
ix$4 = 68
xtile$ = 72
sety$5 = 76
setx$6 = 80
py$7 = 84
vibration$ = 88
input$ = 96
px$8 = 104
height$ = 108
width$ = 112
inWidth$ = 116
$T9 = 120
xr$10 = 124
ytile$ = 128
seed$ = 132
yr$11 = 136
err$ = 140
outWidth$ = 144
inData$ = 152
outData$ = 160
$T12 = 168
suites$ = 176
in_data$ = 1056
out_data$ = 1064
params$ = 1072
output$ = 1080
?dtor$0@?0??Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA PROC ; `Render'::`1'::dtor$0
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
	lea	rcx, QWORD PTR suites$[rbp]
	call	??1AEGP_SuiteHandler@@QEAA@XZ		; AEGP_SuiteHandler::~AEGP_SuiteHandler
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
?dtor$0@?0??Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA ENDP ; `Render'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Odtp
; File c:\users\syuilo\documents\visual studio 2013\projects\after_effects_cs5_sdk_win\adobe after effects cs5 win sdk\examples\template\moonface\skeleton.cpp
_TEXT	SEGMENT
border_y$ = 0
border_x$ = 8
border$ = 16
in_data$ = 48
out_data$ = 56
params$ = 64
output$ = 72
?FrameSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z PROC ; FrameSetup

; 144  : {

	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 145  :     // Output buffer resizing may only occur during PF_Cmd_FRAME_SETUP. 
; 146  : 
; 147  :     double			border_x = 0,

	xorps	xmm0, xmm0
	movsdx	QWORD PTR border_x$[rsp], xmm0

; 148  :         border_y = 0,

	xorps	xmm0, xmm0
	movsdx	QWORD PTR border_y$[rsp], xmm0

; 149  :         border = 0;

	xorps	xmm0, xmm0
	movsdx	QWORD PTR border$[rsp], xmm0

; 150  : 
; 151  :     border_x = border_y = border;

	movsdx	xmm0, QWORD PTR border$[rsp]
	movsdx	QWORD PTR border_y$[rsp], xmm0
	movsdx	xmm0, QWORD PTR border_y$[rsp]
	movsdx	QWORD PTR border_x$[rsp], xmm0

; 152  : 
; 153  : 
; 154  :     // add 2 times the border width and height to the input width and
; 155  :     // height to get the output size.
; 156  : 
; 157  :     out_data->width = 2 * (long)border_x + params[0]->u.ld.width;

	cvttsd2si eax, QWORD PTR border_x$[rsp]
	mov	ecx, 8
	imul	rcx, rcx, 0
	mov	rdx, QWORD PTR params$[rsp]
	mov	rcx, QWORD PTR [rdx+rcx]
	mov	ecx, DWORD PTR [rcx+92]
	lea	eax, DWORD PTR [rcx+rax*2]
	mov	rcx, QWORD PTR out_data$[rsp]
	mov	DWORD PTR [rcx+80], eax

; 158  :     out_data->height = 2 * (long)border_y + params[0]->u.ld.height;

	cvttsd2si eax, QWORD PTR border_y$[rsp]
	mov	ecx, 8
	imul	rcx, rcx, 0
	mov	rdx, QWORD PTR params$[rsp]
	mov	rcx, QWORD PTR [rdx+rcx]
	mov	ecx, DWORD PTR [rcx+96]
	lea	eax, DWORD PTR [rcx+rax*2]
	mov	rcx, QWORD PTR out_data$[rsp]
	mov	DWORD PTR [rcx+84], eax

; 159  : 
; 160  :     // The origin of the input buffer corresponds to the (border_x, 
; 161  :     // border_y) pixel in the output buffer.
; 162  : 
; 163  :     out_data->origin.h = (short)border_x;

	cvttsd2si eax, QWORD PTR border_x$[rsp]
	cwde
	mov	rcx, QWORD PTR out_data$[rsp]
	mov	DWORD PTR [rcx+88], eax

; 164  :     out_data->origin.v = (short)border_y;

	cvttsd2si eax, QWORD PTR border_y$[rsp]
	cwde
	mov	rcx, QWORD PTR out_data$[rsp]
	mov	DWORD PTR [rcx+92], eax

; 165  : 
; 166  :     return PF_Err_NONE;

	xor	eax, eax

; 167  : }

	add	rsp, 40					; 00000028H
	ret	0
?FrameSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z ENDP ; FrameSetup
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\syuilo\documents\visual studio 2013\projects\after_effects_cs5_sdk_win\adobe after effects cs5 win sdk\examples\template\moonface\skeleton.cpp
_TEXT	SEGMENT
priv_err$1 = 32
_t$2 = 36
priv_err$3 = 40
priv_err$4 = 44
_t$5 = 48
_t$6 = 52
_t$7 = 56
priv_err$8 = 60
tv66 = 64
_p$9 = 72
tv89 = 80
_p$10 = 88
tv199 = 96
_p$11 = 104
tv144 = 112
_p$12 = 120
err$ = 128
def$ = 144
__$ArrayPad$ = 320
in_data$ = 352
out_data$ = 360
params$ = 368
output$ = 376
?ParamsSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z PROC ; ParamsSetup

; 91   : {

	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 344				; 00000158H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax

; 92   :     PF_Err		err = PF_Err_NONE;

	mov	DWORD PTR err$[rsp], 0
$LN36@ParamsSetu:

; 93   :     PF_ParamDef	def;
; 94   : 
; 95   :     // ------------------------
; 96   :     AEFX_CLR_STRUCT(def);

	mov	DWORD PTR _t$5[rsp], 176		; 000000b0H
	lea	rax, QWORD PTR def$[rsp]
	mov	QWORD PTR _p$9[rsp], rax
$LN33@ParamsSetu:
	mov	eax, DWORD PTR _t$5[rsp]
	mov	DWORD PTR tv66[rsp], eax
	mov	eax, DWORD PTR _t$5[rsp]
	dec	eax
	mov	DWORD PTR _t$5[rsp], eax
	cmp	DWORD PTR tv66[rsp], 0
	je	SHORT $LN32@ParamsSetu
	mov	rax, QWORD PTR _p$9[rsp]
	mov	BYTE PTR [rax], 0
	mov	rax, QWORD PTR _p$9[rsp]
	inc	rax
	mov	QWORD PTR _p$9[rsp], rax
	jmp	SHORT $LN33@ParamsSetu
$LN32@ParamsSetu:
	xor	eax, eax
	test	eax, eax
	jne	SHORT $LN36@ParamsSetu
$LN31@ParamsSetu:

; 97   :     PF_ADD_SLIDER("Block size",
; 98   :         MOONFACE_SIZE_MIN,
; 99   :         MOONFACE_SIZE_MAX,
; 100  :         MOONFACE_SIZE_MIN,
; 101  :         MOONFACE_SIZE_MAX,
; 102  :         MOONFACE_SIZE_DFLT,
; 103  :         SIZE_DISK_ID);

	mov	DWORD PTR priv_err$3[rsp], 0
	mov	DWORD PTR def$[rsp+12], 1
	mov	rax, QWORD PTR in_data$[rsp]
	mov	rax, QWORD PTR [rax+176]
	lea	rdx, OFFSET FLAT:$SG117840
	lea	rcx, QWORD PTR def$[rsp+16]
	call	QWORD PTR [rax+336]
	mov	eax, 1
	imul	rax, rax, 0
	mov	BYTE PTR def$[rsp+rax+60], 0
	mov	eax, 1
	imul	rax, rax, 0
	mov	BYTE PTR def$[rsp+rax+92], 0
	mov	DWORD PTR def$[rsp+124], 1
	mov	DWORD PTR def$[rsp+132], 1
	mov	DWORD PTR def$[rsp+128], 256		; 00000100H
	mov	DWORD PTR def$[rsp+136], 256		; 00000100H
	mov	DWORD PTR def$[rsp+140], 128		; 00000080H
	mov	eax, DWORD PTR def$[rsp+140]
	mov	DWORD PTR def$[rsp+56], eax
	mov	DWORD PTR def$[rsp], 1
	lea	r8, QWORD PTR def$[rsp]
	mov	edx, -1
	mov	rax, QWORD PTR in_data$[rsp]
	mov	rcx, QWORD PTR [rax+184]
	mov	rax, QWORD PTR in_data$[rsp]
	call	QWORD PTR [rax+16]
	mov	DWORD PTR priv_err$3[rsp], eax
	cmp	DWORD PTR priv_err$3[rsp], 0
	je	SHORT $LN28@ParamsSetu
	mov	eax, DWORD PTR priv_err$3[rsp]
	jmp	$LN37@ParamsSetu
$LN28@ParamsSetu:
	xor	eax, eax
	test	eax, eax
	jne	$LN31@ParamsSetu
$LN27@ParamsSetu:

; 104  : 
; 105  :     // ------------------------
; 106  :     AEFX_CLR_STRUCT(def);

	mov	DWORD PTR _t$7[rsp], 176		; 000000b0H
	lea	rax, QWORD PTR def$[rsp]
	mov	QWORD PTR _p$10[rsp], rax
$LN24@ParamsSetu:
	mov	eax, DWORD PTR _t$7[rsp]
	mov	DWORD PTR tv89[rsp], eax
	mov	eax, DWORD PTR _t$7[rsp]
	dec	eax
	mov	DWORD PTR _t$7[rsp], eax
	cmp	DWORD PTR tv89[rsp], 0
	je	SHORT $LN23@ParamsSetu
	mov	rax, QWORD PTR _p$10[rsp]
	mov	BYTE PTR [rax], 0
	mov	rax, QWORD PTR _p$10[rsp]
	inc	rax
	mov	QWORD PTR _p$10[rsp], rax
	jmp	SHORT $LN24@ParamsSetu
$LN23@ParamsSetu:
	xor	eax, eax
	test	eax, eax
	jne	SHORT $LN27@ParamsSetu
$LN22@ParamsSetu:

; 107  :     PF_ADD_SLIDER("Vibration",
; 108  :         MOONFACE_SIZE_MIN,
; 109  :         MOONFACE_SIZE_MAX,
; 110  :         MOONFACE_SIZE_MIN,
; 111  :         MOONFACE_SIZE_MAX,
; 112  :         MOONFACE_SIZE_DFLT,
; 113  :         VIBRATION_DISK_ID);

	mov	DWORD PTR priv_err$1[rsp], 0
	mov	DWORD PTR def$[rsp+12], 1
	mov	rax, QWORD PTR in_data$[rsp]
	mov	rax, QWORD PTR [rax+176]
	lea	rdx, OFFSET FLAT:$SG117855
	lea	rcx, QWORD PTR def$[rsp+16]
	call	QWORD PTR [rax+336]
	mov	eax, 1
	imul	rax, rax, 0
	mov	BYTE PTR def$[rsp+rax+60], 0
	mov	eax, 1
	imul	rax, rax, 0
	mov	BYTE PTR def$[rsp+rax+92], 0
	mov	DWORD PTR def$[rsp+124], 1
	mov	DWORD PTR def$[rsp+132], 1
	mov	DWORD PTR def$[rsp+128], 256		; 00000100H
	mov	DWORD PTR def$[rsp+136], 256		; 00000100H
	mov	DWORD PTR def$[rsp+140], 128		; 00000080H
	mov	eax, DWORD PTR def$[rsp+140]
	mov	DWORD PTR def$[rsp+56], eax
	mov	DWORD PTR def$[rsp], 2
	lea	r8, QWORD PTR def$[rsp]
	mov	edx, -1
	mov	rax, QWORD PTR in_data$[rsp]
	mov	rcx, QWORD PTR [rax+184]
	mov	rax, QWORD PTR in_data$[rsp]
	call	QWORD PTR [rax+16]
	mov	DWORD PTR priv_err$1[rsp], eax
	cmp	DWORD PTR priv_err$1[rsp], 0
	je	SHORT $LN19@ParamsSetu
	mov	eax, DWORD PTR priv_err$1[rsp]
	jmp	$LN37@ParamsSetu
$LN19@ParamsSetu:
	xor	eax, eax
	test	eax, eax
	jne	$LN22@ParamsSetu
$LN18@ParamsSetu:

; 114  : 
; 115  :     // ------------------------
; 116  :     AEFX_CLR_STRUCT(def);

	mov	DWORD PTR _t$2[rsp], 176		; 000000b0H
	lea	rax, QWORD PTR def$[rsp]
	mov	QWORD PTR _p$11[rsp], rax
$LN15@ParamsSetu:
	mov	eax, DWORD PTR _t$2[rsp]
	mov	DWORD PTR tv144[rsp], eax
	mov	eax, DWORD PTR _t$2[rsp]
	dec	eax
	mov	DWORD PTR _t$2[rsp], eax
	cmp	DWORD PTR tv144[rsp], 0
	je	SHORT $LN14@ParamsSetu
	mov	rax, QWORD PTR _p$11[rsp]
	mov	BYTE PTR [rax], 0
	mov	rax, QWORD PTR _p$11[rsp]
	inc	rax
	mov	QWORD PTR _p$11[rsp], rax
	jmp	SHORT $LN15@ParamsSetu
$LN14@ParamsSetu:
	xor	eax, eax
	test	eax, eax
	jne	SHORT $LN18@ParamsSetu
$LN13@ParamsSetu:

; 117  :     PF_ADD_SLIDER("Random seed",
; 118  :         0,
; 119  :         16384,
; 120  :         0,
; 121  :         16384,
; 122  :         0,
; 123  :         SEED_DISK_ID);

	mov	DWORD PTR priv_err$4[rsp], 0
	mov	DWORD PTR def$[rsp+12], 1
	mov	rax, QWORD PTR in_data$[rsp]
	mov	rax, QWORD PTR [rax+176]
	lea	rdx, OFFSET FLAT:$SG117870
	lea	rcx, QWORD PTR def$[rsp+16]
	call	QWORD PTR [rax+336]
	mov	eax, 1
	imul	rax, rax, 0
	mov	BYTE PTR def$[rsp+rax+60], 0
	mov	eax, 1
	imul	rax, rax, 0
	mov	BYTE PTR def$[rsp+rax+92], 0
	mov	DWORD PTR def$[rsp+124], 0
	mov	DWORD PTR def$[rsp+132], 0
	mov	DWORD PTR def$[rsp+128], 16384		; 00004000H
	mov	DWORD PTR def$[rsp+136], 16384		; 00004000H
	mov	DWORD PTR def$[rsp+140], 0
	mov	eax, DWORD PTR def$[rsp+140]
	mov	DWORD PTR def$[rsp+56], eax
	mov	DWORD PTR def$[rsp], 3
	lea	r8, QWORD PTR def$[rsp]
	mov	edx, -1
	mov	rax, QWORD PTR in_data$[rsp]
	mov	rcx, QWORD PTR [rax+184]
	mov	rax, QWORD PTR in_data$[rsp]
	call	QWORD PTR [rax+16]
	mov	DWORD PTR priv_err$4[rsp], eax
	cmp	DWORD PTR priv_err$4[rsp], 0
	je	SHORT $LN10@ParamsSetu
	mov	eax, DWORD PTR priv_err$4[rsp]
	jmp	$LN37@ParamsSetu
$LN10@ParamsSetu:
	xor	eax, eax
	test	eax, eax
	jne	$LN13@ParamsSetu
$LN9@ParamsSetu:

; 124  : 
; 125  :     // ------------------------
; 126  :     AEFX_CLR_STRUCT(def);

	mov	DWORD PTR _t$6[rsp], 176		; 000000b0H
	lea	rax, QWORD PTR def$[rsp]
	mov	QWORD PTR _p$12[rsp], rax
$LN6@ParamsSetu:
	mov	eax, DWORD PTR _t$6[rsp]
	mov	DWORD PTR tv199[rsp], eax
	mov	eax, DWORD PTR _t$6[rsp]
	dec	eax
	mov	DWORD PTR _t$6[rsp], eax
	cmp	DWORD PTR tv199[rsp], 0
	je	SHORT $LN5@ParamsSetu
	mov	rax, QWORD PTR _p$12[rsp]
	mov	BYTE PTR [rax], 0
	mov	rax, QWORD PTR _p$12[rsp]
	inc	rax
	mov	QWORD PTR _p$12[rsp], rax
	jmp	SHORT $LN6@ParamsSetu
$LN5@ParamsSetu:
	xor	eax, eax
	test	eax, eax
	jne	SHORT $LN9@ParamsSetu
$LN4@ParamsSetu:

; 127  :     PF_ADD_CHECKBOX("Merge",
; 128  :         "”wŒi‚Æ‡¬‚µ‚Ü‚·B",
; 129  :         TRUE,
; 130  :         0,
; 131  :         MERGE_DISK_ID);

	mov	DWORD PTR priv_err$8[rsp], 0
	mov	DWORD PTR def$[rsp+12], 4
	mov	rax, QWORD PTR in_data$[rsp]
	mov	rax, QWORD PTR [rax+176]
	lea	rdx, OFFSET FLAT:$SG117885
	lea	rcx, QWORD PTR def$[rsp+16]
	call	QWORD PTR [rax+336]
	lea	rax, OFFSET FLAT:$SG117886
	mov	QWORD PTR def$[rsp+64], rax
	mov	DWORD PTR def$[rsp+56], 1
	mov	BYTE PTR def$[rsp+60], 1
	mov	eax, DWORD PTR def$[rsp+48]
	mov	DWORD PTR def$[rsp+48], eax
	mov	DWORD PTR def$[rsp], 4
	lea	r8, QWORD PTR def$[rsp]
	mov	edx, -1
	mov	rax, QWORD PTR in_data$[rsp]
	mov	rcx, QWORD PTR [rax+184]
	mov	rax, QWORD PTR in_data$[rsp]
	call	QWORD PTR [rax+16]
	mov	DWORD PTR priv_err$8[rsp], eax
	cmp	DWORD PTR priv_err$8[rsp], 0
	je	SHORT $LN1@ParamsSetu
	mov	eax, DWORD PTR priv_err$8[rsp]
	jmp	SHORT $LN37@ParamsSetu
$LN1@ParamsSetu:
	xor	eax, eax
	test	eax, eax
	jne	$LN4@ParamsSetu

; 132  : 
; 133  :     out_data->num_params = MOONFACE_NUM_PARAMS;

	mov	rax, QWORD PTR out_data$[rsp]
	mov	DWORD PTR [rax+48], 5

; 134  : 
; 135  :     return err;

	mov	eax, DWORD PTR err$[rsp]
$LN37@ParamsSetu:

; 136  : }

	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 344				; 00000158H
	ret	0
?ParamsSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z ENDP ; ParamsSetup
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\syuilo\documents\visual studio 2013\projects\after_effects_cs5_sdk_win\adobe after effects cs5 win sdk\examples\template\moonface\skeleton.cpp
_TEXT	SEGMENT
in_data$ = 8
out_data$ = 16
params$ = 24
output$ = 32
?GlobalSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z PROC ; GlobalSetup

; 67   : {

	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx

; 68   :     out_data->my_version = PF_VERSION(MAJOR_VERSION,
; 69   :         MINOR_VERSION,
; 70   :         BUG_VERSION,
; 71   :         STAGE_VERSION,
; 72   :         BUILD_VERSION);

	mov	rax, QWORD PTR out_data$[rsp]
	mov	DWORD PTR [rax], 524289			; 00080001H

; 73   : 
; 74   :     out_data->out_flags = PF_OutFlag_DEEP_COLOR_AWARE |	// just 16bpc, not 32bpc
; 75   :         PF_OutFlag_I_EXPAND_BUFFER |
; 76   :         PF_OutFlag_I_HAVE_EXTERNAL_DEPENDENCIES;

	mov	rax, QWORD PTR out_data$[rsp]
	mov	DWORD PTR [rax+96], 50332160		; 03000200H

; 77   : 
; 78   :     out_data->out_flags2 = PF_OutFlag2_SUPPORTS_QUERY_DYNAMIC_FLAGS |
; 79   :         PF_OutFlag2_I_USE_3D_CAMERA |
; 80   :         PF_OutFlag2_I_USE_3D_LIGHTS;

	mov	rax, QWORD PTR out_data$[rsp]
	mov	DWORD PTR [rax+400], 7

; 81   : 
; 82   :     return PF_Err_NONE;

	xor	eax, eax

; 83   : }

	ret	0
?GlobalSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z ENDP ; GlobalSetup
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\syuilo\documents\visual studio 2013\projects\after_effects_cs5_sdk_win\adobe after effects cs5 win sdk\examples\template\moonface\skeleton.cpp
_TEXT	SEGMENT
$T1 = 48
tv78 = 56
tv82 = 64
tv73 = 72
$T2 = 80
suites$ = 96
in_data$ = 976
out_data$ = 984
params$ = 992
output$ = 1000
?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z PROC ; About

; 49   : {

	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 968				; 000003c8H
	mov	QWORD PTR $T2[rsp], -2

; 50   :     AEGP_SuiteHandler suites(in_data->pica_basicP);

	mov	rax, QWORD PTR in_data$[rsp]
	mov	rdx, QWORD PTR [rax+384]
	lea	rcx, QWORD PTR suites$[rsp]
	call	??0AEGP_SuiteHandler@@QEAA@PEBUSPBasicSuite@@@Z ; AEGP_SuiteHandler::AEGP_SuiteHandler
	npad	1

; 51   : 
; 52   :     suites.ANSICallbacksSuite1()->sprintf(out_data->return_msg,
; 53   :         "%s v%d.%d\r%s",
; 54   :         STR(StrID_Name),
; 55   :         MAJOR_VERSION,
; 56   :         MINOR_VERSION,
; 57   :         STR(StrID_Description));

	mov	ecx, 2
	call	GetStringPtr
	mov	QWORD PTR tv73[rsp], rax
	mov	ecx, 1
	call	GetStringPtr
	mov	QWORD PTR tv78[rsp], rax
	mov	rcx, QWORD PTR out_data$[rsp]
	add	rcx, 100				; 00000064H
	mov	QWORD PTR tv82[rsp], rcx
	lea	rcx, QWORD PTR suites$[rsp]
	call	?ANSICallbacksSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_ANSICallbacksSuite1@@XZ ; AEGP_SuiteHandler::ANSICallbacksSuite1
	mov	rcx, QWORD PTR tv73[rsp]
	mov	QWORD PTR [rsp+40], rcx
	mov	QWORD PTR [rsp+32], 0
	mov	r9d, 1
	mov	rcx, QWORD PTR tv78[rsp]
	mov	r8, rcx
	lea	rdx, OFFSET FLAT:$SG117805
	mov	rcx, QWORD PTR tv82[rsp]
	call	QWORD PTR [rax+120]

; 58   :     return PF_Err_NONE;

	mov	DWORD PTR $T1[rsp], 0
	lea	rcx, QWORD PTR suites$[rsp]
	call	??1AEGP_SuiteHandler@@QEAA@XZ		; AEGP_SuiteHandler::~AEGP_SuiteHandler
	mov	eax, DWORD PTR $T1[rsp]

; 59   : }

	add	rsp, 968				; 000003c8H
	ret	0
?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z ENDP ; About
_TEXT	ENDS
; Function compile flags: /Odtp
text$x	SEGMENT
$T1 = 48
tv78 = 56
tv82 = 64
tv73 = 72
$T2 = 80
suites$ = 96
in_data$ = 976
out_data$ = 984
params$ = 992
output$ = 1000
?dtor$0@?0??About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA PROC ; `About'::`1'::dtor$0
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
	lea	rcx, QWORD PTR suites$[rbp]
	call	??1AEGP_SuiteHandler@@QEAA@XZ		; AEGP_SuiteHandler::~AEGP_SuiteHandler
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
?dtor$0@?0??About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z@4HA ENDP ; `About'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Odtp
; File c:\users\syuilo\documents\visual studio 2013\projects\after_effects_cs5_sdk_win\adobe after effects cs5 win sdk\examples\template\moonface\skeleton.cpp
_TEXT	SEGMENT
err$ = 32
tv64 = 36
tv137 = 40
tv138 = 44
tv139 = 48
tv136 = 52
tv140 = 56
tv135 = 60
tv134 = 64
$T1 = 72
thrown_err$2 = 80
cmd$ = 112
in_data$ = 120
out_data$ = 128
params$ = 136
output$ = 144
extra$ = 152
EntryPointFunc PROC

; 349  : {

$LN19:
	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 104				; 00000068H
	mov	QWORD PTR $T1[rsp], -2

; 350  :     PF_Err		err = PF_Err_NONE;

	mov	DWORD PTR err$[rsp], 0

; 351  : 
; 352  :     try {
; 353  :         switch (cmd) {

	mov	eax, DWORD PTR cmd$[rsp]
	mov	DWORD PTR tv64[rsp], eax
	cmp	DWORD PTR tv64[rsp], 18
	ja	$LN8@EntryPoint
	movsxd	rax, DWORD PTR tv64[rsp]
	lea	rcx, OFFSET FLAT:__ImageBase
	mov	eax, DWORD PTR $LN17@EntryPoint[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN7@EntryPoint:

; 354  :         case PF_Cmd_ABOUT:
; 355  : 
; 356  :             err = About(in_data,
; 357  :                 out_data,
; 358  :                 params,
; 359  :                 output);

	mov	r9, QWORD PTR output$[rsp]
	mov	r8, QWORD PTR params$[rsp]
	mov	rdx, QWORD PTR out_data$[rsp]
	mov	rcx, QWORD PTR in_data$[rsp]
	call	?About@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z ; About
	mov	DWORD PTR tv134[rsp], eax
	mov	eax, DWORD PTR tv134[rsp]
	mov	DWORD PTR err$[rsp], eax

; 360  :             break;

	jmp	$LN8@EntryPoint
$LN6@EntryPoint:

; 361  : 
; 362  :         case PF_Cmd_GLOBAL_SETUP:
; 363  : 
; 364  :             err = GlobalSetup(in_data,
; 365  :                 out_data,
; 366  :                 params,
; 367  :                 output);

	mov	r9, QWORD PTR output$[rsp]
	mov	r8, QWORD PTR params$[rsp]
	mov	rdx, QWORD PTR out_data$[rsp]
	mov	rcx, QWORD PTR in_data$[rsp]
	call	?GlobalSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z ; GlobalSetup
	mov	DWORD PTR tv135[rsp], eax
	mov	eax, DWORD PTR tv135[rsp]
	mov	DWORD PTR err$[rsp], eax

; 368  :             break;

	jmp	$LN8@EntryPoint
$LN5@EntryPoint:

; 369  : 
; 370  :         case PF_Cmd_PARAMS_SETUP:
; 371  : 
; 372  :             err = ParamsSetup(in_data,
; 373  :                 out_data,
; 374  :                 params,
; 375  :                 output);

	mov	r9, QWORD PTR output$[rsp]
	mov	r8, QWORD PTR params$[rsp]
	mov	rdx, QWORD PTR out_data$[rsp]
	mov	rcx, QWORD PTR in_data$[rsp]
	call	?ParamsSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z ; ParamsSetup
	mov	DWORD PTR tv136[rsp], eax
	mov	eax, DWORD PTR tv136[rsp]
	mov	DWORD PTR err$[rsp], eax

; 376  :             break;

	jmp	$LN8@EntryPoint
$LN4@EntryPoint:

; 377  : 
; 378  :         case PF_Cmd_FRAME_SETUP:
; 379  : 
; 380  :             err = FrameSetup(in_data,
; 381  :                 out_data,
; 382  :                 params,
; 383  :                 output);

	mov	r9, QWORD PTR output$[rsp]
	mov	r8, QWORD PTR params$[rsp]
	mov	rdx, QWORD PTR out_data$[rsp]
	mov	rcx, QWORD PTR in_data$[rsp]
	call	?FrameSetup@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z ; FrameSetup
	mov	DWORD PTR tv137[rsp], eax
	mov	eax, DWORD PTR tv137[rsp]
	mov	DWORD PTR err$[rsp], eax

; 384  :             break;

	jmp	$LN8@EntryPoint
$LN3@EntryPoint:

; 385  : 
; 386  :         case PF_Cmd_RENDER:
; 387  : 
; 388  :             err = Render(in_data,
; 389  :                 out_data,
; 390  :                 params,
; 391  :                 output);

	mov	r9, QWORD PTR output$[rsp]
	mov	r8, QWORD PTR params$[rsp]
	mov	rdx, QWORD PTR out_data$[rsp]
	mov	rcx, QWORD PTR in_data$[rsp]
	call	?Render@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAUPF_LayerDef@@@Z ; Render
	mov	DWORD PTR tv138[rsp], eax
	mov	eax, DWORD PTR tv138[rsp]
	mov	DWORD PTR err$[rsp], eax

; 392  :             break;

	jmp	SHORT $LN8@EntryPoint
$LN2@EntryPoint:

; 393  : 
; 394  :         case PF_Cmd_GET_EXTERNAL_DEPENDENCIES:
; 395  : 
; 396  :             err = DescribeDependencies(in_data,
; 397  :                 out_data,
; 398  :                 params,
; 399  :                 extra);

	mov	r9, QWORD PTR extra$[rsp]
	mov	r8, QWORD PTR params$[rsp]
	mov	rdx, QWORD PTR out_data$[rsp]
	mov	rcx, QWORD PTR in_data$[rsp]
	call	?DescribeDependencies@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z ; DescribeDependencies
	mov	DWORD PTR tv139[rsp], eax
	mov	eax, DWORD PTR tv139[rsp]
	mov	DWORD PTR err$[rsp], eax

; 400  :             break;

	jmp	SHORT $LN8@EntryPoint
$LN1@EntryPoint:

; 401  : 
; 402  :         case PF_Cmd_QUERY_DYNAMIC_FLAGS:
; 403  : 
; 404  :             err = QueryDynamicFlags(in_data,
; 405  :                 out_data,
; 406  :                 params,
; 407  :                 extra);

	mov	r9, QWORD PTR extra$[rsp]
	mov	r8, QWORD PTR params$[rsp]
	mov	rdx, QWORD PTR out_data$[rsp]
	mov	rcx, QWORD PTR in_data$[rsp]
	call	?QueryDynamicFlags@@YAJPEAUPF_InData@@PEAUPF_OutData@@QEAPEAUPF_ParamDef@@PEAX@Z ; QueryDynamicFlags
	mov	DWORD PTR tv140[rsp], eax
	mov	eax, DWORD PTR tv140[rsp]
	mov	DWORD PTR err$[rsp], eax
$LN8@EntryPoint:
	jmp	SHORT $LN15@EntryPoint
$LN16@EntryPoint:
$LN15@EntryPoint:

; 408  :             break;
; 409  :         }
; 410  :     }
; 411  :     catch (PF_Err &thrown_err){
; 412  :         err = thrown_err;
; 413  :     }
; 414  :     return err;

	mov	eax, DWORD PTR err$[rsp]

; 415  : }

	add	rsp, 104				; 00000068H
	ret	0
$LN17@EntryPoint:
	DD	$LN7@EntryPoint
	DD	$LN6@EntryPoint
	DD	$LN8@EntryPoint
	DD	$LN8@EntryPoint
	DD	$LN5@EntryPoint
	DD	$LN8@EntryPoint
	DD	$LN8@EntryPoint
	DD	$LN8@EntryPoint
	DD	$LN8@EntryPoint
	DD	$LN8@EntryPoint
	DD	$LN4@EntryPoint
	DD	$LN3@EntryPoint
	DD	$LN8@EntryPoint
	DD	$LN8@EntryPoint
	DD	$LN8@EntryPoint
	DD	$LN8@EntryPoint
	DD	$LN2@EntryPoint
	DD	$LN8@EntryPoint
	DD	$LN1@EntryPoint
EntryPointFunc ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
text$x	SEGMENT
err$ = 32
tv64 = 36
tv137 = 40
tv138 = 44
tv139 = 48
tv136 = 52
tv140 = 56
tv135 = 60
tv134 = 64
$T1 = 72
thrown_err$2 = 80
cmd$ = 112
in_data$ = 120
out_data$ = 128
params$ = 136
output$ = 144
extra$ = 152
EntryPointFunc$catch$0 PROC

; 411  :     catch (PF_Err &thrown_err){

	mov	QWORD PTR [rsp+16], rdx
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
__catch$EntryPointFunc$0:

; 412  :         err = thrown_err;

	mov	rax, QWORD PTR thrown_err$2[rbp]
	mov	eax, DWORD PTR [rax]
	mov	DWORD PTR err$[rbp], eax

; 413  :     }

	lea	rax, $LN16@EntryPoint
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
	int	3
EntryPointFunc$catch$0 ENDP
text$x	ENDS
; Function compile flags: /Odtp
; File c:\users\syuilo\documents\visual studio 2013\projects\after_effects_cs5_sdk_win\adobe after effects cs5 win sdk\examples\util\aegp_suitehandler.h
;	COMDAT ?HandleSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_HandleSuite1@@XZ
_TEXT	SEGMENT
this$ = 48
?HandleSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_HandleSuite1@@XZ PROC ; AEGP_SuiteHandler::HandleSuite1, COMDAT

; 418  : 	AEGP_SUITE_ACCESS_BOILERPLATE(HandleSuite, 1, PF_, handle_suite1P, kPFHandleSuite, kPFHandleSuiteVersion1);

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	mov	rax, QWORD PTR this$[rsp]
	cmp	QWORD PTR [rax+320], 0
	jne	SHORT $LN1@HandleSuit
	mov	r8d, 2
	lea	rdx, OFFSET FLAT:??_C@_0BA@CLDKMHPO@PF?5Handle?5Suite?$AA@
	mov	rcx, QWORD PTR this$[rsp]
	call	?LoadSuite@AEGP_SuiteHandler@@AEBAPEAXPEADJ@Z ; AEGP_SuiteHandler::LoadSuite
	mov	rcx, QWORD PTR this$[rsp]
	mov	QWORD PTR [rcx+320], rax
$LN1@HandleSuit:
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax+320]
	add	rsp, 40					; 00000028H
	ret	0
?HandleSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_HandleSuite1@@XZ ENDP ; AEGP_SuiteHandler::HandleSuite1
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\syuilo\documents\visual studio 2013\projects\after_effects_cs5_sdk_win\adobe after effects cs5 win sdk\examples\util\aegp_suitehandler.h
;	COMDAT ?ANSICallbacksSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_ANSICallbacksSuite1@@XZ
_TEXT	SEGMENT
this$ = 48
?ANSICallbacksSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_ANSICallbacksSuite1@@XZ PROC ; AEGP_SuiteHandler::ANSICallbacksSuite1, COMDAT

; 417  : 	AEGP_SUITE_ACCESS_BOILERPLATE(ANSICallbacksSuite, 1, PF_, ansi_callbacks_suite1P, kPFANSISuite, kPFANSISuiteVersion1);

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	mov	rax, QWORD PTR this$[rsp]
	cmp	QWORD PTR [rax+312], 0
	jne	SHORT $LN1@ANSICallba
	mov	r8d, 1
	lea	rdx, OFFSET FLAT:??_C@_0O@JPGHEGPP@PF?5ANSI?5Suite?$AA@
	mov	rcx, QWORD PTR this$[rsp]
	call	?LoadSuite@AEGP_SuiteHandler@@AEBAPEAXPEADJ@Z ; AEGP_SuiteHandler::LoadSuite
	mov	rcx, QWORD PTR this$[rsp]
	mov	QWORD PTR [rcx+312], rax
$LN1@ANSICallba:
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax+312]
	add	rsp, 40					; 00000028H
	ret	0
?ANSICallbacksSuite1@AEGP_SuiteHandler@@QEBAPEAUPF_ANSICallbacksSuite1@@XZ ENDP ; AEGP_SuiteHandler::ANSICallbacksSuite1
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\syuilo\documents\visual studio 2013\projects\after_effects_cs5_sdk_win\adobe after effects cs5 win sdk\examples\util\aegp_suitehandler.h
;	COMDAT ?LoadSuite@AEGP_SuiteHandler@@AEBAPEAXPEADJ@Z
_TEXT	SEGMENT
err$ = 32
suiteP$ = 40
this$ = 64
nameZ$ = 72
versionL$ = 80
?LoadSuite@AEGP_SuiteHandler@@AEBAPEAXPEADJ@Z PROC	; AEGP_SuiteHandler::LoadSuite, COMDAT

; 218  : 	{

$LN5:
	mov	DWORD PTR [rsp+24], r8d
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 219  : 		const void *suiteP;
; 220  : 		A_long err = i_pica_basicP->AcquireSuite(nameZ, versionL, &suiteP);

	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	lea	r8, QWORD PTR suiteP$[rsp]
	mov	edx, DWORD PTR versionL$[rsp]
	mov	rcx, QWORD PTR nameZ$[rsp]
	call	QWORD PTR [rax]
	mov	DWORD PTR err$[rsp], eax

; 221  : 
; 222  : 		if (err || !suiteP) {

	cmp	DWORD PTR err$[rsp], 0
	jne	SHORT $LN1@LoadSuite
	cmp	QWORD PTR suiteP$[rsp], 0
	jne	SHORT $LN2@LoadSuite
$LN1@LoadSuite:

; 223  : 			MissingSuiteError();

	mov	rcx, QWORD PTR this$[rsp]
	call	?MissingSuiteError@AEGP_SuiteHandler@@AEBAXXZ ; AEGP_SuiteHandler::MissingSuiteError
$LN2@LoadSuite:

; 224  : 		}
; 225  : 
; 226  : 		return (void*)suiteP;

	mov	rax, QWORD PTR suiteP$[rsp]

; 227  : 	}

	add	rsp, 56					; 00000038H
	ret	0
?LoadSuite@AEGP_SuiteHandler@@AEBAPEAXPEADJ@Z ENDP	; AEGP_SuiteHandler::LoadSuite
_TEXT	ENDS
END
